name: Build Sphinx and Deploy
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target Environment'
        required: true
        default: 'github-pages'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-sphinx-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      # checkout the source code
      - name: Checkout Repository
        uses: actions/checkout@v5
      # set up python environment
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install sphinx sphinx_rtd_theme myst_parser
      - name: Sphinx build
        run: |
          cd docs && sphinx-build source build/html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: docs
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
